functions:
  jira-worklog-webhook:
    events:
      - http:
          path: /
          method: post
    handler: handler.worklogWebhook
package:
  exclude:
    - 'yarn.lock'
    - '.**'
plugins:
  - serverless-plugin-include-dependencies
provider:
  name: aws
  environment:
    AWS_PROFILE: ${self:provider.profile}
  # Needed in order to access the S3 bucket defined by ori-rsa-keygen
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  profile: ori
  runtime: nodejs6.10
  stage: prod
service: jira-worklog-webhook
